apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: {{.Values.app.name}}
  labels:
    heritage: {{.Values.app.name}}
  annotations:
    component.deis.io/version: {{.Values.image.tag}}
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  selector:
    matchLabels:
      app: {{.Values.app.name}}
  template:
    metadata:
      labels:
        app: {{.Values.app.name}}
    spec:
      serviceAccount: {{.Values.app.name}}
      containers:
        - name: {{.Values.app.name}}
          image: {{.Values.image.registry}}/{{.Values.image.org}}/{{.Values.image.name}}:{{.Values.image.tag}}
          imagePullPolicy: {{.Values.image.pull_policy}}
          env:
            - name: MONGO_HOST
              value: {{.Values.app.name}}-mongodb
          livenessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /healthz
              port: 8080
            initialDelaySeconds: 10
            timeoutSeconds: 10
          ports:
            - containerPort: 8080
              name: http
{{- if or (.Values.resources.limits_cpu) (.Values.resources.limits_memory)}}
          resources:
            limits:
{{- if (.Values.resources.limits_cpu) }}
              cpu: {{.Values.resources.limits_cpu}}
{{- end}}
{{- if (.Values.resources.limits_memory) }}
              memory: {{.Values.resources.limits_memory}}
{{- end}}
{{- end}}